language: java
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - stage: test
      name: "OracleJDK 8"
      jdk: oraclejdk8
      script: mvn -q clean verify -B
    - if: type != pull_request
      name: "OpenJDK 11"
      jdk: openjdk11
      script: mvn -q clean verify -B
    - stage: deploy
      name: "Deploy to Sonatype's snapshots repository"
      if: type != pull_request AND env(SONATYPE_NEXUS_USERNAME) IS present
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - secure: "4sLceyLVg5fTqAmweX0d8nMx1jF2qspU/HDoJrunzQFTS1qG9WWpMaU1aM0Kd/sEfYJW6H6psswplYywt14mVbDVjg7BWmu79u1rdMp1Ij3aB8n5xdPsvYcuYuT5Q+FjP+zXoZI5pU/1ZLPx+lJe77F8WQUkFqQfshNTqTlsRrS7HL/4vTD7xtEqbpQz8sEcHsjxajRkrMpMaRiy/0oE0dADY6ZKDidw85T8+Ifo0aKr9TIC4X2660ZjcokVyOzC1oJztTB1yer0tYES07VjGdZkJ1l7uKkaPO8p2ol+3QmyjqUSWcAWf81iZbSDEpH6CVtMmNjMdj7OInx5bh+Me+PlrO2+oFhiJBo/VUV6ragOOQZYwcPjpFdvgJUH6JzRVoGnRx9igdHQKusohugc7Qs1+cCVNclh6TeegbmZeP84KJdBjdthnnAQOPQenyiAESbC3t8vEPZMARcFZWXUeK9KWQ5zQWPCf6CRk2ObeScdHuQXnUUZOelySrvl/k/OaHvDaGScKkRwY4h5W7VHhcKZP10pyYzqrAY8FMbFC1KHX423mINS3FcrR211wdtsPw1Dwq3IAEX7VoLcVoVSUrwfqJcm5XJrXsvAvsepcFWF7iRhCeecq6nTJyfGtPgrCTXcQB/xYgrLdXjzoZntkluewiftLeD8dygrfsyJmwc="
    on_success: always
    on_failure: always
