// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streaming.proto

package examples;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streaming.Empty)
    com.google.protobuf.MessageOrBuilder {
}
